service: compiler
image: ghcr.io/usecompiler/compiler

ssh:
  user: ubuntu

proxy:
  ssl: true
  forward_headers: true
  app_port: 3000
  healthcheck:
    path: /up
    interval: 3
    timeout: 30

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    APP_MODE: saas
    EMAIL_FROM: noreply@notifications.usecompiler.com
    REDIS_URL: redis://compiler-redis:6379
  secret:
    - DATABASE_URL
    - TOKEN_ENCRYPTION_KEY
    - GITHUB_APP_ID
    - GITHUB_APP_SLUG
    - GITHUB_APP_PRIVATE_KEY
    - E2B_API_KEY
    - ANTHROPIC_API_KEY
    - GITHUB_WEBHOOK_SECRET
    - GITHUB_APP_CLIENT_ID
    - GITHUB_APP_CLIENT_SECRET
    - RESEND_API_KEY

builder:
  arch: arm64
  dockerfile: Dockerfile
  context: ..

accessories:
  redis:
    image: redis:7-alpine
    roles:
      - web
    volumes:
      - /var/lib/compiler-redis:/data

